[env]
LAMBDA_ARCH="linux/amd64"
RUST_VERSION="latest"
RUST_TARGET="x86_64-unknown-linux-gnu"

[tasks.buildlambda]
description = "build lambda using docker for cross compile"
script = '''
docker run \
  --platform ${LAMBDA_ARCH} \
  --rm --user "$(id -u)":"$(id -g)" \
  -v "${PWD}":/usr/src/myapp -w /usr/src/myapp rust:${RUST_VERSION} \
  cargo build --release --target ${RUST_TARGET}
'''

[tasks.packagelambda]
command = "zip"
args = ["-j", "target/rust.zip", "target/x86_64-unknown-linux-gnu/release/bootstrap"]
dependencies = ["buildlambda"]