[package]
name = "add-numbers-api"
version = "0.1.0"
edition = "2021"
autobins = false

[dependencies]
lambda_http = "0.4.1"
serde = "^1"
serde_json = "^1"
serde_derive = "^1"
log = "^0.4"
tokio = { version = "1.15", features = ["full"] }

[[bin]]
name = "bootstrap"
path = "src/main.rs"
